apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    name: products
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: products